//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenTechnology.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class Cancion
    {
        public int idCancion { get; set; }
        [DataMember]
        public string nombreCancion { get; set; }
        [DataMember]
        public Nullable<int> idCantante { get; set; }
       
        public virtual Cantante Cantante { get; set; }
    }
}
